#!/usr/bin/env bash

set -euo pipefail

echo "🚀 Hello! You are going to install the Milfist dotfiles. Make sure it is what you need."
echo "---------------------------------------------------------------------------------------"
echo
export DOT="$HOME/.dotfiles"
echo "👉  Cloning into: '$DOT'"

# To test that git is installed (if not macOS will prompt an installer)
git --version

git clone --depth 1 https://github.com/Milfist/dotfiles.git "$DOT"


# Brew install
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install Brewfile
brew bundle --file=brew/Brewfile

# dotfiles Setup (need Stow)
"$DOT/setup" self install

